### GENERAL SETTINGS ###

# Site settings
title: "Techno Culture Club"
description: "Le point de rencontre entre la culture et la technologie"
analytics: "" #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://technoculture.club"

# Build settings
markdown: kramdown
permalink: /:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#000000" 
  primary_rgb: "30,30,30" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#ffffff" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#bfc9d3"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/technocultureclub
  - title: twitter
    url: http://twitter.com/technocultureclub
  - title: linkedin
    url: http://www.linkedin.com/company/technocultureclub

    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - TechnoCulture Club
    - "7255 Alexandra #203"
    - "Montréal, QC"
email: bonjour@technoculture.club
tel: 438 398 5784


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: 
    position: 
    text:
    img:
    site: 
    tel: 
    social: 
    - title: envelope
      url: 
  - name: 
    position: 
    text:
    img:
    site: 
    tel: 
    social: 
    - title: envelope
      url: 
  - name: 
    position: 
    text:
    img:
    site: 
    tel: 
    social: 
    - title: envelope
      url: 
  - name: 
    position: 
    text:
    img:
    site: 
    tel: 
    social: 
    - title: envelope
      url: 
    
# Clients information. Shown on Home and About pages.
clients:
  - name: Visiativ
    img: visiativ.png
    link: http://www.visiativ.com/
  - name: ERASME
    img: erasme.png
    link: http://www.erasme.org/
  - name: valpre
    img: valpre.png
    link: http://www.valpre.com/
  - name: meetings
    img: meetings.png
    link: http://www.meetings.fr/
    
# Principes de travail 
principes:
  - name: Rencontre
    faicon: comments
    texte: "créer des contextes de rencontre et de création entre les communautés technologiques et culturelles."
  - name:  Résilience
    faicon: connectdevelop
    texte: "développer des outils permettant à cette communauté émergente d'apprendre et de se soutenir elle-même."
  - name: Ouverture
    faicon: unlock
    texte: "encourager le partage et la création de 'commun' entre ses membres."

# Events
projects: 
  - name: Museomix MTL 
    link: http://museomixmtl.com
    logo: 
  - name: Space Apps Challenge 
    link: http://spaceappschallenge.com/montreal
    logo: 
  - name: SuperFund (bientôt)
    link: http://superfund.technoculture.club 
    logo: 
# Questions 
questions: 
  - titre: "La communauté est-elle ouverte à tous ?"
    reponse: "Oui, bien sûr. Nous sommes en train de mettre en place des outils pour discuter et s'organiser. Mais en attendant, la première étape serait de participer à un des événements organisés prochainement."
    n: 1
  - titre: "J'ai une idée de projet. Est-ce que je peux le présenter ?"
    reponse: "Tous les projets qui peuvent nourrir cette la communauté techno-culturelle sont les bienvenus. Contactez-nous pour en discuter !"
    n: 2

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "techno culture club : à l'intersection de la culture et de la technologie."
about_plus: ""

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO
